#!/bin/sh /etc/rc.common
# Saguaro Core — procd servis

START=95
STOP=10
USE_PROCD=1
PROG=/opt/saguaro/bin/saguaro-core

start_service() {
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
